/* Page-specific behavior extracted from inline scripts during v6 cleanup. */
document.querySelectorAll('.tab').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active')}));
const pickupDate=document.getElementById('pickupDate'), returnDate=document.getElementById('returnDate');
if(pickupDate&&returnDate){pickupDate.addEventListener('change',()=>{ if(returnDate.value && returnDate.value < pickupDate.value){ returnDate.value = pickupDate.value; } returnDate.min = pickupDate.value; }); returnDate.min=pickupDate.value;}
document.getElementById('reserveBtn')?.addEventListener('click',()=>{const params=new URLSearchParams({pickupDate:pickupDate.value,pickupTime:document.getElementById('pickupTime').value,returnDate:returnDate.value,returnTime:document.getElementById('returnTime').value});window.location.href='rezervacija-vozila.html?'+params.toString();});
let automaticOnly=true; const autoSwitch=document.getElementById('autoSwitch'), classFilter=document.getElementById('classFilter'), fuelFilter=document.getElementById('fuelFilter'), cards=[...document.querySelectorAll('.car-card')], empty=document.getElementById('emptyState');
function applyFilters(){const cls=classFilter.value, fuel=fuelFilter.value; let visible=0; cards.forEach(card=>{const okClass=cls==='all'||card.dataset.class===cls; const okFuel=fuel==='all'||card.dataset.fuel===fuel; const okAuto=!automaticOnly||card.dataset.auto==='true'; const show=okClass&&okFuel&&okAuto; card.classList.toggle('is-hidden',!show); if(show) visible++;}); empty.style.display=visible?'none':'block';}
if(autoSwitch) autoSwitch.addEventListener('click',()=>{automaticOnly=!automaticOnly; autoSwitch.classList.toggle('off',!automaticOnly); autoSwitch.setAttribute('aria-pressed',String(automaticOnly)); applyFilters();});
classFilter?.addEventListener('change',applyFilters); fuelFilter?.addEventListener('change',applyFilters); applyFilters();
